before_script:
  - javac -version

stages:
  - test
  - deploy

maven_test:
  stage: test
  script:
    - "mvn test"

maven_deploy:
  stage: deploy
  script:
    - "mvn deploy"
  artifacts:
    expire_in: 1 week
    paths:
      - target/*.jar
      - target/*.asc
      - target/*.pom